"""

#NOTE THIS WAS GENERATED BY CLAUDE WITH MINIMAL EDITS - SEE EMCode.nb for the actual code used by the authors. 

data_extraction.py

Downloads FIB-SEM data from the public OpenOrganelle S3 repository and saves
the 2D slices used by EMCode.nb as CSV files. No account or credentials needed.

Datasets:
  jrc_hela-3  https://www.openorganelle.org/datasets/jrc_hela-3
  jrc_jurkat-1  https://www.openorganelle.org/datasets/jrc_jurkat-1

Install dependencies:
  pip install fsspec s3fs "zarr<3" dask numpy

  Note: zarr v3 removed N5FSStore and is not compatible with this script.

Run:
  python data_extraction.py

Output:
  Six CSV files saved to the same directory as this script. Place them in the
  same folder as EMCode.nb before opening the notebook.
"""

import fsspec
import zarr
import dask.array as da
import numpy as np
import os

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

DATASETS = {
    "jrc_hela-3": "s3://janelia-cosem-datasets/jrc_hela-3/jrc_hela-3.n5",
    "jrc_jurkat-1": "s3://janelia-cosem-datasets/jrc_jurkat-1/jrc_jurkat-1.n5",
}

# Each entry: (dataset_key, output_filename, z, y_start, y_end, x_start, x_end)
# Set y/x bounds to None to extract the full axis extent (equivalent to :)
SLICES = [
    ("jrc_hela-3",   "jrc_hela-3_x6290_6700_y250_500_z5740.csv",    5740,  250,  500,  6290, 6700),
    ("jrc_hela-3",   "jrc_hela-3_x5301_5711_y233_483_z5730.csv",    5730,  233,  483,  5301, 5711),
    ("jrc_hela-3",   "jrc_hela-3_x5297_5707_y440_690_z5584.csv",    5584,  440,  690,  5297, 5707),
    ("jrc_hela-3",   "jrc_hela-3_x5938_6348_y336_586_z5660.csv",    5660,  336,  586,  5938, 6348),
    ("jrc_jurkat-1", "jrc_jurkat-1_x7763_8173_y926_1176_z3788.csv", 3788,  926, 1176,  7763, 8173),
    # Full z-plane — no x/y crop. This file is large and is the only
    # one not included in the repository. None:None slices give the full axis extent.
    ("jrc_hela-3",   "jrc_hela-3_z5740.csv",                        5740, None, None,  None, None),
]


def load_dataset(s3_path):
    print(f"  Connecting to {s3_path} ...")
    store = zarr.N5FSStore(s3_path, anon=True)
    group = zarr.open(store)
    zdata = group["em/fibsem-uint16/s0"]
    return da.from_array(zdata, chunks=zdata.chunks)


def extract_and_save(ddata, z, y_start, y_end, x_start, x_end, output_path):
    result = ddata[z, y_start:y_end, x_start:x_end].compute()
    np.savetxt(output_path, result, fmt="%d", delimiter=",")
    size_mb = os.path.getsize(output_path) / 1_048_576
    print(f"  Saved {os.path.basename(output_path)} ({result.shape[0]}x{result.shape[1]}, {size_mb:.1f} MB)")


def main():
    loaded = {}

    for dataset_key, filename, z, y_start, y_end, x_start, x_end in SLICES:
        output_path = os.path.join(OUTPUT_DIR, filename)

        if os.path.exists(output_path):
            print(f"Skipping {filename} (already exists)")
            continue

        print(f"Extracting {filename} ...")

        if dataset_key not in loaded:
            loaded[dataset_key] = load_dataset(DATASETS[dataset_key])

        extract_and_save(loaded[dataset_key], z, y_start, y_end, x_start, x_end, output_path)

    print("\nDone. Place all CSV files in the same folder as EMCode.nb.")


if __name__ == "__main__":
    main()
